resources:
- name: concourse-demo-meetup-5
  type: git
  source:
    uri: git@github.com:shinji62/concourse-demo-meetup-5.git
    branch: master
    private_key: {{private-key-github-concourse}}

- name: alpine-golang-bash
  type: docker-image
  source:
    repository: getourneau/alpine-golang-bash
    tag: latest

- name: mysql-image
  type: docker-image
  source:
    repository: mysql
    tag: 5.6





jobs:

- name: testing-with-mysql
  public: true
  serial: true
  plan:
  - aggregate:
    - get: source-repos
      resource: concourse-demo-meetup-5
    - get: mysql-image
      params: {save: true}
    - get: alpine-golang-bash
      params: {save: true}
  - task: Run-testing
    file: source-repos/ci/testing/testing.yml
