db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: meetup
app:
  image: getourneau/alpine-golang-bash
  volumes:
    - ../../:/go/src/github.com/shinji62/concourse-demo-meetup-5
  working_dir: /go/src/github.com/shinji62/concourse-demo-meetup-5
  environment:
    DATASOURCE_TEST: "root:root@tcp(db:3306)/meetup"
  command: make test
  links:
    - "db:mysql"
